### ISSUE TITLE
[BUG] SSH terminal stuttering persists — ssh2 native crypto fails to compile on Node 26 (V8 API incompatibility)

### ISSUE THREAD

**Issue by Qiuser** [Termix-SSH/Support#869]
### Description

Issue #767 identified that missing `ssh2` native crypto causes SSH terminal stuttering. The Dockerfile was updated to include `ssh2` in `npm rebuild`, but **the fix is ineffective because ssh2 v1.17.0's native addon cannot compile on Node 26** (V8 14.6 removed `Context::GetIsolate()`).

The current Docker image (`ghcr.io/lukegus/termix:latest`) ships without `sshcrypto.node`, falling back to the pure-JS crypto implementation which blocks the event loop under high-frequency SSH data.

### Proof: Native addon is missing in current image

```bash
docker exec <container> find /app/node_modules/ssh2 -name "*.node"
# (no output — sshcrypto.node does not exist)

docker exec <container> ls /app/node_modules/ssh2/lib/protocol/crypto/build/Release/
# .deps/  obj.target/
# (build started but linking failed — no .node produced)
```

### Root Cause: V8 API breakage in Node 26

ssh2 v1.17.0's C++ binding uses `v8::Context::GetIsolate()` which was removed in V8 14.6 (Node 26). The compilation fails with:

```
../src/binding.cc:89:37: error: 'class v8::Context' has no member named 'GetIsolate'
```

This error occurs at 6 call sites in `binding.cc` (lines 89, 423, 664, 1061, 1489, 1741).

### One-command reproduction

**Fails on Node 26:**
```bash
docker run --rm node:26-slim sh -c \
  'apt-get update -qq && apt-get install -y -qq python3 make g++ wget >/dev/null 2>&1 && \
  npm init -y >/dev/null 2>&1 && npm install ssh2@1.17.0 --ignore-scripts >/dev/null 2>&1 && \
  mkdir -p /tmp/nh && cd /tmp/nh && \
  wget -q https://nodejs.org/download/release/$(node -v)/node-$(node -v)-headers.tar.gz && \
  tar xzf *.tar.gz && cd /root && \
  cd node_modules/ssh2/lib/protocol/crypto && \
  npx --yes node-gyp rebuild --nodedir=/tmp/nh/node-$(node -v) 2>&1 | grep -E "error:|\.node"'
```
Expected output:
```
../src/binding.cc:89:37: error: 'class v8::Context' has no member named 'GetIsolate'
(repeated 6 times, no .node file produced)
```

**Succeeds on Node 24:**
```bash
docker run --rm node:24-slim sh -c \
  'apt-get update -qq && apt-get install -y -qq python3 make g++ wget >/dev/null 2>&1 && \
  npm init -y >/dev/null 2>&1 && npm install ssh2@1.17.0 --ignore-scripts >/dev/null 2>&1 && \
  mkdir -p /tmp/nh && cd /tmp/nh && \
  wget -q https://nodejs.org/download/release/$(node -v)/node-$(node -v)-headers.tar.gz && \
  tar xzf *.tar.gz && cd /root && \
  cd node_modules/ssh2/lib/protocol/crypto && \
  npx --yes node-gyp rebuild --nodedir=/tmp/nh/node-$(node -v) 2>&1 | grep -E "error:|\.node"'
```
Expected output:
```
COPY Release/sshcrypto.node
```

### Performance impact (from #767)

| Metric | Without native crypto (Node 26) | With native crypto (Node 22/24) |
|--------|---|---|
| p95 frame gap | 60ms | 21ms |
| Frame drops (>50ms) | 17.4% | 0.1% |
| Perceived smoothness | Stuttery, rhythmic pauses | Smooth |

### Fix

The Node 26 upgrade came from Dependabot (#914) with no functional dependency on Node 26 features. Downgrade the Dockerfile base image to Node 24 (or Node 22 LTS):

```diff
-FROM node:26-slim AS deps
+FROM node:24-slim AS deps
...
-FROM node:26-slim AS production-deps
+FROM node:24-slim AS production-deps
...
-FROM node:26-slim
+FROM node:24-slim
```

This restores native crypto compilation and resolves the terminal stuttering.

### Environment

- Termix version: 2.4.0
- Docker image: `ghcr.io/lukegus/termix:latest` (Node 26.3.1)
- ssh2 version: 1.17.0
- Related: #767
